FROM node:24.11-alpine

RUN corepack enable

WORKDIR /usr/src/app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./

COPY packages/shared/package.json ./packages/shared/

COPY apps/frontend/package.json ./apps/frontend/

RUN pnpm install

COPY packages/shared ./packages/shared
COPY apps/frontend ./apps/frontend

RUN pnpm --filter @repo/shared build

WORKDIR /usr/src/app/apps/frontend

EXPOSE 5173

CMD ["pnpm", "dev", "--host"]